variables:
  # The GIT_DEPTH option makes the project clone process in each job a bit faster, pulling only the current commit, not the whole Git history.
  GIT_DEPTH: "1"
  # overlay2 filesystem for the Docker build, which is faster and less space consuming
  DOCKER_DRIVER: overlay2
  # Abilita debug gitlab-ci
  #CI_DEBUG_TRACE: "true"

stages:
  - test:serialize
  - test:sparql

.base:
  image: python:3.8.12
  variables:
    RDF_FILE_NAME: test-serialize-rdf
    OWL_FILE_NAME: test-serialize-owl
  before_script:
    - pip install -r requirements.txt

# TEST SERIALIZE
test-serialize:
  extends: .base
  stage: test:serialize
  script:
    - python wsn-ffd-rdf.py $RDF_FILE_NAME
    - python wsn-ffd-owl.py $OWL_FILE_NAME
  artifacts:
    paths:
      - "${RDF_FILE_NAME}-xml.rdf"
      - "${RDF_FILE_NAME}-pretty-xml.rdf"
      - "${RDF_FILE_NAME}-turtle.ttl"
      - "${OWL_FILE_NAME}-xml.rdf"
      - "${OWL_FILE_NAME}-pretty-xml.rdf"
      - "${OWL_FILE_NAME}-turtle.ttl"
    expire_in: 1 days

#TEST SPARQL
test-sparql:
  extends: .base
  stage: test:sparql
  script:
    - python test_sparql.py "${OWL_FILE_NAME}-xml.rdf" "${OWL_FILE_NAME}-pretty-xml.rdf"
    - python test_sparql.py "${OWL_FILE_NAME}-pretty-xml.rdf" "${OWL_FILE_NAME}-turtle.ttl"
